#!/bin/bash

wclean libraries/customFunctions

wcleanLnIncludeAll libraries/customTurbulenceModels/turbulenceModels
wclean libraries/customTurbulenceModels/compressible

wclean libraries/aerosolThermo
wclean libraries/aerosolModels

wclean applications/solvers/aerosolEulerFoam
wclean applications/solvers/aerosolEulerFoam/aerosolBuoyantEulerFoam

wclean applications/test/aerosolThermo

wclean applications/utilities/setSaturatedMixture
wclean applications/utilities/setLogNormal
