#!/bin/bash

wmake libso libraries/customFunctions

wmakeLnInclude libraries/customTurbulenceModels/turbulenceModels
wmake libso libraries/customTurbulenceModels/compressible

wmake libso libraries/aerosolThermo
wmake libso libraries/aerosolModels

wmake applications/solvers/aerosolEulerFoam
wmake applications/solvers/aerosolEulerFoam/aerosolBuoyantEulerFoam

wmake applications/test/aerosolThermo

wmake applications/utilities/setSaturatedMixture
wmake applications/utilities/setLogNormal
